### ISSUE TITLE
Git sources

### ISSUE THREAD

**Issue by simonask** [simonask/fatso#6]
Implement fetching source code from a Git repository with a URL and a branch or a tag.

Packages should be able to define their source like so:

```
project: foo
version: 1.1
source:
    git: https://github.com/foo/foo.git
    ref: releases/v1.1
```
